### ISSUE TITLE
Home cover section src property of image error.. how do i resolve this?

### ISSUE THREAD

**Issue by iamskp544** [codebucks27/Nextjs-tailwindcss-blog-template#1]
Error: Image with src "" has "placeholder='blur'" property but is missing the "blurDataURL" property.
        Possible solutions:
          - Add a "blurDataURL" property, the contents should be a small Data URL to represent the image
          - Change the "src" property to a static import with one of the supported file types: jpeg,png,webp,avif (animated images not supported)
          - Remove the "placeholder" property, effectively no blur effect
        Read more: https://nextjs.org/docs/messages/placeholder-blur-data-url

**Comment by codebucks27** [comment]
> Error: Image with src "" has "placeholder='blur'" property but is missing the "blurDataURL" property. Possible solutions: - Add a "blurDataURL" property, the contents should be a small Data URL to represent the image - Change the "src" property to a static import with one of the supported file types: jpeg,png,webp,avif (animated images not supported) - Remove the "placeholder" property, effectively no blur effect Read more: https://nextjs.org/docs/messages/placeholder-blur-data-url

Hey, Cover section component has blurDataURL prop. 
Can you send the screenshot of the error that you are getting?

**Comment by iamskp544** [comment]
![image](https://github.com/codebucks27/Nextjs-tailwindcss-blog-template/assets/123294530/3593fa97-d358-48f3-9b28-3b31d1a79eab)
![image](https://github.com/codebucks27/Nextjs-tailwindcss-blog-template/assets/123294530/35e70631-85da-445d-aeed-fd5ed10148c9)

**Comment by codebucks27** [comment]
> ![image](https://user-images.githubusercontent.com/123294530/270178460-3593fa97-d358-48f3-9b28-3b31d1a79eab.png) ![image](https://user-images.githubusercontent.com/123294530/270178504-35e70631-85da-445d-aeed-fd5ed10148c9.png)

Hey, Which version of the Node.js are you using? I'm not getting any error I have checked this again.
