### ISSUE TITLE
README Update to include instructions about how to setup the Supabase for this template

### ISSUE THREAD

**Issue by sharansudheer** [codebucks27/Nextjs-tailwindcss-blog-template#6]
Hi @codebucks27,

Right now, when I download this project and do npm i and npm run dev, it leads to an error if I click on any of the Blog articles - Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!. The error is getting traced back to the file src/components/Blog/ViewCounter.js. 

I am not able to understand where I need to instantiate the env variables
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY= 
Should it be in a separate .env file, I couldn't clearly understand in which file the connection with a supabase project that we have to create separately was instantiated

**Comment by AveyBD** [comment]
To resolve the error related to missing Supabase environment variables in your Next.js project, follow these steps:

1. **Create a file named `.env.local`**: This file should be placed in the root directory of your project.

2. **Set the environment variables**: Within the `.env.local` file, define the required environment variables for Supabase:

   ```
   NEXT_PUBLIC_SUPABASE_URL=yourURL
   NEXT_PUBLIC_SUPABASE_ANON_KEY=yourKey
   ```

   Replace `yourURL` with the URL of your Supabase project and `yourKey` with the anonymous key associated with your Supabase project.

3. **Restart the development server**: After setting up the environment variables, restart your development server to apply the changes and ensure that the variables are properly loaded into your Next.js project.

By following these steps and providing the appropriate values for your  project, you should be able to resolve the error and successfully connect your Next.js application to Supabase.

**Comment by codebucks27** [comment]
> Hi @codebucks27,
> 
> Right now, when I download this project and do npm i and npm run dev, it leads to an error if I click on any of the Blog articles - Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!. The error is getting traced back to the file src/components/Blog/ViewCounter.js.
> 
> I am not able to understand where I need to instantiate the env variables NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co NEXT_PUBLIC_SUPABASE_ANON_KEY= SUPABASE_SERVICE_ROLE_KEY= Should it be in a separate .env file, I couldn't clearly understand in which file the connection with a supabase project that we have to create separately was instantiated

Please follow the instructions given in this video: [Use Supasbase to add view count in a next.js blog](https://www.youtube.com/watch?v=1QGLHOaRLwM&t=15785s)
